FROM microsoft/aspnetcore-build
ENV ASPNETCORE_URLS http://+:80
WORKDIR /app
COPY project.json .
RUN dotnet restore
COPY Program.cs .
COPY Startup.cs .

RUN dotnet publish --output /out/. --configuration Release

#Build your image:
 #$ docker build -t build-image -f Dockerfile.build .
#Create a container from your image and copy your built application out.
 #$ docker create --name build-cont build-image
 #$ docker cp build-cont:/out ./output
